// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL-23SZT5pFIqyglLS-B4E8fPtuJAlFfQ',
    appId: '1:692572630696:web:3b1db264bdd59c572e5c9d',
    messagingSenderId: '692572630696',
    projectId: 'ai-travelplanner-d2859',
    authDomain: 'ai-travelplanner-d2859.firebaseapp.com',
    storageBucket: 'ai-travelplanner-d2859.firebasestorage.app',
    measurementId: 'G-KSNWTH3PJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Y9xaP-cV5-kDYss9cRU8KDGQtxfSv7U',
    appId: '1:692572630696:android:17bea2fa769f69f72e5c9d',
    messagingSenderId: '692572630696',
    projectId: 'ai-travelplanner-d2859',
    storageBucket: 'ai-travelplanner-d2859.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Y0LzmLnnc8fTcaZLRH9up-uAXYbKyUc',
    appId: '1:692572630696:ios:fb48115c948aa49e2e5c9d',
    messagingSenderId: '692572630696',
    projectId: 'ai-travelplanner-d2859',
    storageBucket: 'ai-travelplanner-d2859.firebasestorage.app',
    iosBundleId: 'com.example.aiTravelmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3Y0LzmLnnc8fTcaZLRH9up-uAXYbKyUc',
    appId: '1:692572630696:ios:fb48115c948aa49e2e5c9d',
    messagingSenderId: '692572630696',
    projectId: 'ai-travelplanner-d2859',
    storageBucket: 'ai-travelplanner-d2859.firebasestorage.app',
    iosBundleId: 'com.example.aiTravelmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL-23SZT5pFIqyglLS-B4E8fPtuJAlFfQ',
    appId: '1:692572630696:web:11bd6a9ecc79b6e32e5c9d',
    messagingSenderId: '692572630696',
    projectId: 'ai-travelplanner-d2859',
    authDomain: 'ai-travelplanner-d2859.firebaseapp.com',
    storageBucket: 'ai-travelplanner-d2859.firebasestorage.app',
    measurementId: 'G-D51YQ2022T',
  );
}
